name: Factory Data Sync

on:
  schedule:
    # This runs every hour, on the hour.
    - cron: '0 * * * *'
  workflow_dispatch: # Allows you to also run it manually from GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas google-cloud-bigquery gspread google-auth db-dtypes

      - name: Run Migration
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          # This temporary file helps GitHub "see" your credentials safely
          echo "$GCP_SA_KEY" > dcs-system-494410-5488af32c0c7.json
          python migrate.py
