name: Factory Data Sync

on:
  workflow_dispatch:  # <-- Button in Sheets will hit this

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas google-cloud-bigquery gspread google-auth db-dtypes

      - name: Run Migration
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" > dcs-system-494410-5488af32c0c7.json
          python migrate.py
